"""CLI to generate a synthetic dataset from a named scenario.

    python -m rippletwin.data.generate --scenario S1_HIDDEN_BOTTLENECK --out data/raw

Writes the model-input tables and the evaluation-only ground truth into separate
files, and a manifest recording exactly which seeds produced them.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from ..factory import scenarios as SC
from ..factory.topology import build_line
from ..twin.pipeline import simulate

MODEL_INPUT = ("telemetry", "inspections", "vehicles", "environment")
EVAL_ONLY = ("passes", "disturbances", "defects")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Generate a RippleTwin dataset")
    ap.add_argument("--scenario", default="S1_HIDDEN_BOTTLENECK",
                    choices=list(SC.FLAGSHIP_SCENARIOS) + ["NOMINAL"])
    ap.add_argument("--config", default="configs/line_42.yaml")
    ap.add_argument("--line-seed", type=int, default=7)
    ap.add_argument("--sim-seed", type=int, default=20260301)
    ap.add_argument("--vehicles", type=int, default=0,
                    help="override the scenario's vehicle count")
    ap.add_argument("--out", default="data/raw")
    args = ap.parse_args(argv)

    line = build_line(args.config, seed=args.line_seed)
    scen = (
        SC.nominal_run(args.vehicles or 2600)
        if args.scenario == "NOMINAL"
        else SC.FLAGSHIP_SCENARIOS[args.scenario](line)
    )
    if args.vehicles:
        scen.n_vehicles = args.vehicles

    res = simulate(line, scen, seed=args.sim_seed)

    out = Path(args.out) / scen.scenario_id
    out.mkdir(parents=True, exist_ok=True)
    for name in MODEL_INPUT + EVAL_ONLY:
        getattr(res, name).to_csv(out / f"{name}.csv", index=False)

    manifest = {
        "scenario": scen.scenario_id,
        "title": scen.title,
        "notes": scen.notes,
        "line_config": args.config,
        "line_seed": args.line_seed,
        "sim_seed": args.sim_seed,
        "model_input_files": [f"{n}.csv" for n in MODEL_INPUT],
        "evaluation_only_files": [f"{n}.csv" for n in EVAL_ONLY],
        "line": line.summary(),
        "meta": res.meta,
        "warning": (
            "SYNTHETIC DATA. Generated by simulation, not measured from any real "
            "production line. Files listed under evaluation_only_files must never "
            "be given to the model."
        ),
    }
    (out / "manifest.json").write_text(json.dumps(manifest, indent=2, default=str))

    print(f"wrote {len(MODEL_INPUT) + len(EVAL_ONLY)} tables to {out}")
    print(f"  model input     : {', '.join(MODEL_INPUT)}")
    print(f"  evaluation only : {', '.join(EVAL_ONLY)}")
    print(f"  {res.meta['n_vehicles']} vehicles, "
          f"{len(res.telemetry):,} telemetry rows from "
          f"{res.telemetry['station'].nunique()} instrumented stations "
          f"({len(line.hidden_indices)} stations emit nothing)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
